package com.anri.pgcompare.report;

import com.anri.pgcompare.ddl.DdlGenerator;
import com.anri.pgcompare.ddl.DdlStatement;
import com.anri.pgcompare.diff.SchemaDiff;
import com.anri.pgcompare.exception.CompareException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * Renders DdlGenerator output into a runnable .sql migration script.
 */
@Component
@RequiredArgsConstructor
public class SqlScriptWriter {

    private final DdlGenerator ddlGenerator;

    public void write(SchemaDiff diff, Path outputFile) {
        List<DdlStatement> statements = ddlGenerator.generate(diff);
        StringBuilder script = new StringBuilder();
        script.append("-- Migration generated by pg-compare\n")
                .append("-- Transforms schema '%s' into '%s'\n"
                        .formatted(diff.sourceSchema(), diff.targetSchema()))
                .append("-- Generated: %s\n".formatted(OffsetDateTime.now()))
                .append("-- Review BREAKING statements before executing.\n\n");
        for (DdlStatement statement : statements) {
            if (statement.comment() != null) {
                script.append("-- ").append(statement.comment()).append('\n');
            }
            script.append(statement.sql()).append(";\n\n");
        }
        try {
            Path parent = outputFile.toAbsolutePath().getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            Files.writeString(outputFile, script.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new CompareException("Cannot write DDL script to %s: %s".formatted(outputFile, e.getMessage()), e);
        }
    }
}
