package com.anri.pgcompare.report;

import com.anri.pgcompare.ddl.DdlGenerator;
import com.anri.pgcompare.ddl.DdlStatement;
import com.anri.pgcompare.diff.SchemaDiff;
import com.anri.pgcompare.exception.CompareException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * Оформляет результат {@link DdlGenerator} как исполняемый .sql-скрипт миграции: шапка,
 * служебные комментарии перед операторами, {@code ;} после каждого оператора и — по запросу —
 * обёртка из одной транзакции. Текст шапки и комментариев в скрипте остаётся английским:
 * скрипт — артефакт, его сравнивают между прогонами и подают в {@code psql}.
 */
@Component
@RequiredArgsConstructor
public class SqlScriptWriter {

    /** Преобразует различия в упорядоченный набор операторов. */
    private final DdlGenerator ddlGenerator;

    /**
     * Генерирует скрипт и перезаписывает им файл, при необходимости создавая родительские
     * каталоги. Пустой дифф даёт скрипт без операторов — запуск такого файла безопасен.
     *
     * @param diff          результат сравнения (источник мигрирует к цели)
     * @param outputFile    путь .sql-скрипта (аргумент {@code --ddl})
     * @param transactional оборачивать ли операторы в {@code BEGIN}/{@code COMMIT}
     * @throws CompareException если файл не удалось записать
     */
    public void write(SchemaDiff diff, Path outputFile, boolean transactional) {
        List<DdlStatement> statements = ddlGenerator.generate(diff);
        StringBuilder script = new StringBuilder();
        script.append("-- Migration generated by pg-compare\n")
                .append("-- Transforms schema '%s' into '%s'\n"
                        .formatted(diff.sourceSchema(), diff.targetSchema()))
                .append("-- Generated: %s\n".formatted(OffsetDateTime.now()))
                .append("-- Review BREAKING statements before executing.\n")
                .append("-- Run with: psql --set ON_ERROR_STOP=1 -f <this file>\n");
        if (statements.isEmpty()) {
            script.append("\n-- Schemas are identical, nothing to migrate.\n");
        } else {
            // Транзакция — способ не оставить схему на полпути; без неё об этом предупреждает шапка.
            if (transactional) {
                script.append("\n-- One transaction: a failing statement leaves the schema untouched.\n")
                        .append("BEGIN;\n\n");
            } else {
                script.append("\n-- Not wrapped: a failing statement leaves a partially migrated schema.\n");
            }
            for (DdlStatement statement : statements) {
                if (statement.comment() != null) {
                    script.append("-- ").append(statement.comment()).append('\n');
                }
                script.append(statement.sql()).append(";\n\n");
            }
            if (transactional) {
                script.append("COMMIT;\n");
            }
        }
        try {
            Path parent = outputFile.toAbsolutePath().getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            Files.writeString(outputFile, script.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new CompareException("Не удалось записать DDL-скрипт в %s: %s"
                    .formatted(outputFile, e.getMessage()), e);
        }
    }
}
